export const GET_SU_USER_BEGIN = 'GET_SU_USER_BEGIN'
export const SET_SU_USERS_LIST = 'SET_SU_USERS_LIST'
export const GET_SU_USER_FAILURE = 'GET_SU_USER_FAILURE'
export const SET_SU_USER = '@su/SET_SU_USER'